apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiz-app
  template:
    metadata:
      labels:
        app: wiz-app
    spec:
      containers:
      - name: wiz-app
        image: us-central1-docker.pkg.dev/clgcporg10-170/wiz-app-repo/wiz-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: wiz-db-secrets
              key: MONGO_URL---
apiVersion: v1
kind: Service
metadata:
  name: wiz-app-service
spec:
  type: LoadBalancer
  selector:
    app: wiz-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
