apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # Cluster-wide admin role 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiz-app
  template:
    metadata:
      labels:
        app: wiz-app
    spec:
      containers:
      - name: wiz-app
        image: us-central1-docker.pkg.dev/clgcporg59-p001/wiz-app-repo/wiz-app:latest
        securityContext:
          privileged: true # Container has root-level access to the host 
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: wiz-db-secrets
              key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: wiz-app-service
spec:
  type: LoadBalancer # Exposing app to public
  selector:
    app: wiz-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
