name: "Application Build and Deploy"
on:
  push:
    paths:
      - 'app.js'
      - 'Dockerfile'
      - 'package.json'
      - 'k8s/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/427684558345/locations/global/workloadIdentityPools/wiz-pool/providers/wiz-provider"
          service_account: "github-deployer@clgcporg10-170.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Docker Auth"
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: "Build and Push Image"
        run: |
          docker build -t us-central1-docker.pkg.dev/clgcporg10-170/wiz-app-repo/wiz-app:latest .
          docker push us-central1-docker.pkg.dev/clgcporg10-170/wiz-app-repo/wiz-app:latest

      - name: "Deploy to GKE"
        run: |
          gcloud container clusters get-credentials wiz-cluster --zone us-central1-a
          kubectl apply -f k8s/
          kubectl rollout restart deployment/wiz-app
