name: "Application Build and Deploy"

on:
  push:
    branches: 
      - main
      - sumitwiz

# CRITICAL: This permission block is required for Workload Identity Federation
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "projects/220563082991/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-deployer@clgcporg59-p001.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - name: "Docker Auth"
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: "Build and Push Image to Artifact Registry"
        run: |
          docker build -t us-central1-docker.pkg.dev/clgcporg59-p001/wiz-app-repo/wiz-app:latest .
          docker push us-central1-docker.pkg.dev/clgcporg59-p001/wiz-app-repo/wiz-app:latest
          
      - name: "Build local image for scanning"
        run: docker build -t wiz-app:latest .

      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'wiz-app:latest'
          format: 'table'
          exit-code: '0' # Keeps the pipeline running so you can show the results
          severity: 'CRITICAL,HIGH'
          
      - name: "Deploy to GKE"
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials wiz-cluster --zone us-central1-a
          kubectl apply -f k8s/
          kubectl rollout restart deployment/wiz-app
