name: "Application Build and Deploy"
on:
  push:
    branches: '**'
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/427684558345/locations/global/workloadIdentityPools/wiz-pool/providers/wiz-provider"
          service_account: "github-deployer@clgcporg10-170.iam.gserviceaccount.com"
      - uses: "google-github-actions/setup-gcloud@v2"
      - name: "Docker Auth"
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: "Build and Push Image"
        run: |
          docker build -t us-central1-docker.pkg.dev/clgcporg10-170/wiz-app-repo/wiz-app:latest .
          docker push us-central1-docker.pkg.dev/clgcporg10-170/wiz-app-repo/wiz-app:latest
      - name: Build local image for scanning
        run: docker build -t wiz-app:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'wiz-app:latest'
          format: 'table'
          exit-code: '0' # Keeps the pipeline running so you can show the results
          severity: 'CRITICAL,HIGH'
          
      - name: "Deploy to GKE"
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials wiz-cluster --zone us-central1-a
          kubectl apply -f k8s/
          kubectl rollout restart deployment/wiz-app
